#spring boot oauth application with client and user credentials from the database
server:
  port: 8081
  servlet:
    context-path: /springboot-oauth-db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_oauth?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
          hibernate:
            show_sql: true
            format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace